import car1 from "./assets/car1.png";
import car2 from "./assets/car2.png";
import car3 from "./assets/car3.png";
import car4 from "./assets/car4.png";
import car5 from "./assets/car5.png";
import car6 from "./assets/car6.png";
export const data = [
  {
    name: "Toyota RAV 4",
    year: 2012,
    people: 4,
    fuel: "hybrid",
    kmpl: 6.2,
    engine: "automatic",
    price: 450,
    image: car1,
  },
  {
    name: "BMW 3 Series",
    year: 2023,
    people: 2,
    fuel: "gasoline",
    kmpl: 7.2,
    engine: "automatic",
    price: 500,
    image: car2,
  },
  {
    name: "Volkswagen T-Cross",
    year: 2036,
    people: 6,
    fuel: "gasoline",
    kmpl: 4.2,
    engine: "automatic",
    price: 400,
    image: car3,
  },
  {
    name: "Cadillac Escalade",
    year: 2020,
    people: 10,
    fuel: "hybrid",
    kmpl: 9.0,
    engine: "automatic",
    price: 750,
    image: car4,
  },
  {
    name: "GT 90",
    year: 2012,
    people: 4,
    fuel: "gasoline",
    kmpl: 8.2,
    engine: "automatic",
    price: 850,
    image: car5,
  },
  {
    name: "BMW 4 Series",
    year: 2023,
    people: 4,
    fuel: "gasoline",
    kmpl: 6.2,
    engine: "automatic",
    price: 350,
    image: car6,
  },
  {
    name: "BMW 3 Series",
    year: 2016,
    people: 4,
    fuel: "gasoline",
    kmpl: 6.2,
    engine: "automatic",
    price: 450,
    image: car6,
  },
  {
    name: "Rolls Royles",
    year: 2009,
    people: 4,
    fuel: "hybrid",
    kmpl: 6.2,
    engine: "automatic",
    price: 1050,
    image: car3,
  },
  {
    name: "Nano 500",
    year: 2010,
    people: 4,
    fuel: "gasoline",
    kmpl: 8.2,
    engine: "automatic",
    price: 450,
    image: car1,
  },
  {
    name: "Toyota RAV 4",
    year: 2012,
    people: 4,
    fuel: "gasoline",
    kmpl: 6.2,
    engine: "automatic",
    price: 450,
    image: car5,
  },
  {
    name: "GTR 300",
    year: 2012,
    people: 2,
    fuel: "hybrid",
    kmpl: 6.2,
    engine: "automatic",
    price: 450,
    image: car4,
  },
  {
    name: "Force 680",
    year: 2005,
    people: 4,
    fuel: "gasoline",
    kmpl: 6.2,
    engine: "automatic",
    price: 750,
    image: car2,
  },
];
